services:
  pofolit-be:
    container_name: pofolit_be
    restart: always
    build: .
#    image: ruukr8080/pofolit:1.0.0 # docker build -t ruukr8080/pofolit:1.0.0 . docker pull ruukr8080/pofolit:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.env
  mysql:
    image: 'mysql:latest'
    container_name: pofolit_db
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_DATABASE=pofolitdb'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: pofolit-redis
    restart: always
    ports:
      - "6379:6379"
volumes:
  mysql-data: